### ISSUE TITLE
ipcRenderer and ipcMain examples

### ISSUE THREAD

**Issue by soupman99** [alex8088/electron-vite-boilerplate#6]
I looked a bit but didn't see any examples of how to use messaging between process in a svelte application.

Can you give some hints?

when I try `import { ipcRenderer } from "electron";` in a TS render process file I get the error:

`browser-external:path:9 Module "path" has been externalized for browser compatibility. Cannot access "path.join" in client code.
get @ browser-external:path:9
index.js:4 Uncaught ReferenceError: __dirname is not defined
    at node_modules/electron/index.js (index.js:4:28)
    at __require2 (chunk-7FP5O474.js?v=b49c6588:10:50)
    at index.js:21:34`

**Comment by soupman99** [comment]
Nevermind, I kept trying and got it working.  Thanks for the great project starter!
