### ISSUE TITLE
when i yarn install, it failed

### ISSUE THREAD

**Issue by Zhengkang-Zhang** [alex8088/electron-vite-boilerplate#8]
>yarn install
yarn install v1.22.19
warning package.json: No license field
warning ..\package.json: No license field
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning electron-app@1.0.0: No license field
[1/4] Resolving packages...
warning electron-builder > app-builder-lib > electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
warning electron-builder > app-builder-lib > @electron/universal > asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
warning vue > @vue/compiler-sfc > magic-string > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/3] ⠄ electron
[-/3] ⡀ waiting...
error E:\VSCode\React\chatpot\v0.0.1\electron-vite-boilerplate\node_modules\electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: E:\VSCode\React\chatpot\v0.0.1\electron-vite-boilerplate\node_modules\electron
Output:
RequestError: connect ETIMEDOUT 185.199.110.133:443
    at ClientRequest.<anonymous> (E:\VSCode\React\chatpot\v0.0.1\electron-vite-boilerplate\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at origin.emit (E:\VSCode\React\chatpot\v0.0.1\electron-vite-boilerplate\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)

**Comment by alex8088** [comment]
`ETIMEDOUT`, Check your network
